### ISSUE TITLE
SVC values as strings or JSON Object?

### ISSUE THREAD

**Issue by peppelinux** [oauthstuff/draft-selective-disclosure-jwt#81] opened 2022-06-24 23:18 UTC
actually we have the SVC claims dumped as string, in this way

````
"sub": "[\"eluV5Og3gSNII8EYnsxA_A\", \"6c5c0a49-b589-431d-bae7-219122a9ec2c\"]",
````

is there any requirement to have these as strings or this is only an implementation flavour?
Wouldn't be better to have the claims values, in this JSON Object, as JSON Object as well?

this proposal makes the claims values as follows

````
"sub": ["eluV5Og3gSNII8EYnsxA_A", "6c5c0a49-b589-431d-bae7-219122a9ec2c"],
````

This would reduce the encoding/parsing of the values as JSON Object during validation and also improve the readability, removing the escape characters provided by the json dump operation of the object as string.

**Comment by peppelinux** [comment] 2022-06-24 23:29
Ok, I can answer by myself, it seems to me that it's only a rapresentation of the artifacts in stdout

````
[1] > draft-selective-disclosure-jwt/sd_jwt/bin/sd_jwt(160)<module>()
-> print_repr(("Payload of the SD-JWT Salt/Value Container (SVC):",

(Pdb++) 
[1] > draft-selective-disclosure-jwt/sd_jwt/bin/sd_jwt(161)<module>()
-> json.dumps(svc_payload, indent=_args.indent)))

(Pdb++) svc_payload
{'sd_release': {'sub': '["2GLC42sKQveCfGfryNRN9w", "6c5c0a49-b589-431d-bae7-219122a9ec2c"]', 'given_name': '["eluV5Og3gSNII8EYnsxA_A", "John"]', 'family_name': '["6Ij7tM-a5iVPGboS5tmvVA", "Doe"]', 'email': '["eI8ZWm9QnKPpNPeNenHdhQ", "johndoe@example.com"]', 'phone_number': '["Qg_O64zqAxe412a108iroA", "+1-202-555-0101"]', 'address': {'street_address': '["AJx-095VPrpTtN4QMOqROA", "123 Main St"]', 'locality': '["Pc33JM2LchcU_lHggv_ufQ", "Anytown"]', 'region': '["G02NSrQfjFXQ7Io09syajA", "Anystate"]', 'country': '["lklxF5jMYlGTPUovMNIvCA", "US"]'}, 'birthdate': '["nPuoQnkRFq3BIeAm7AnXFA", "1940-01-01"]'}}
````

But this behaviour, related to the demo in the python code, produced this result even in the non normative examples of the specs (eg: [here](https://github.com/oauthstuff/draft-selective-disclosure-jwt/blob/master/main.md#example-sd-jwt-release-for-example-1))

I'd suggest to remove the json.dumps from the demo print operations in stdout

**Comment by danielfett** [comment] 2022-06-25 15:24
This is a duplicate of https://github.com/oauthstuff/draft-selective-disclosure-jwt/issues/27 - please see the discussion there.

**Closed by danielfett** 2022-06-25 15:24 UTC

**Comment by peppelinux** [comment] 2022-06-25 20:23
thank you @danielfett , I completely missed it!
