### ISSUE TITLE
Including an encrypted version of the SD-JWT Salt/Value Container (SVC) in the SD-JWT

### ISSUE THREAD

**Issue by PieterKas** [oauthstuff/draft-selective-disclosure-jwt#33] opened 2022-06-08 11:30 UTC
It may be interesting to consider including the SD-JWT Salt/Value Container (SVC) in the SD-JWT. This way there would be only one structure to pass around and it won't be possible to mix-up SD-JWT Salt/Value Container (SVC) and SD-JWT pairings. The SD-JWT Salt/Value Container (SVC) can be encrypted using a holder public key (using a dedicated encryption key), so privacy is preserved, and only the holder can decrypt that part of the structure before doing a selective disclosure. It also prevent errors where the developer may get confused and send the SD-JWT Salt/Value Container (SVC) to a verifier. 

If the information is already encrypted, the developer only needs to store the single structure and it would be privacy preserving at rest by default (to circumvent the default privacy at rest feature of the data structure, the developer would need to do extra work to decrypt and store the information in clear text - something that can be called out as a risk in the security considerations).

The downside is a larger data structure and the need for encryption keys and should be weighed against the convenience of dealing with a single data structure.

**Comment by Sakurann** [comment] 2022-06-10 21:32
How is this issue different from #37, @PieterKas ?

**Comment by PieterKas** [comment] 2022-06-13 11:40
https://github.com/oauthstuff/draft-selective-disclosure-jwt/issues/37 is broader and covers not just encapsulation of the SVC in the SD-JWT, but also the encapsulation of the SD-JWT in the SD-JWT-R.

**Comment by selfissued** [comment] 2022-06-13 12:38
I am against requiring encryption as part of the basic SD-JWT data structure. We should be emulating the simplicity of mDL's use of salted hashes and stop there.

**Comment by PieterKas** [comment] 2022-06-13 14:01
If we are pursuing a strategy of concatenation rather than encapsulation, the linking between the data structures needs to be clear (e.g. verification of all hashes before accepting that the data structures should be paired).

**Comment by Sakurann** [comment] 2022-07-11 16:33
Closing as a duplicate of Issue #37

**Closed by Sakurann** 2022-07-11 16:33 UTC
Labels: duplicate
